### PR TITLE
[opal] WIP unique deps for pairs of cells

### PR DESCRIPTION
**Pull request by JanKoelzer**
whenNext/whenComplete deps can be registered only once for a pair of cells

### CODE REVIEW

**Comment by JanKoelzer** [comment]
Hopefully, this solves OPAL's need for #113 .

**Comment by amuttsch** [comment]
The result of `whenSequential` or `when` can be misleading. `whenSequential` may return false even if a `next` callback has registered. This can happen if a `complete` callback has already been set up, but no `next` callback. If the client calls `when`, it registers a `next` callback, but since a `complete` callback already exists, it will return `false`.

**Comment by amuttsch** [comment]
I'd say (d) is the correct solution. Otherwise we cannot distinguish if a callback was registered or not.

**Comment by JanKoelzer** [comment]
You could with (c), though. If `whenSequential(…)` returns `(false, true)`, only a complete dependency would have been registered. With (d), you could not decide, why the method failed (either for next dependency or complete dependency already exist).
So does OPAL have a use case for the return value that we could base the decision for (c) or (d) on?

**Comment by phaller** [comment]
I added "WIP" to the title until we have settled on the API.

**Comment by JanKoelzer** [comment]
This PR does now implement (c) as this seems to be an improvement to (a) and (b).
(d) is implemented in #132 .

**Comment by JanKoelzer** [comment]
Andreas and I prefer (d). So I close this PR in favour of #132.

**Pull request closed without merging**
